---
driver:
  name: vagrant
  synced_folders:
    - ["ansible/test", "/tmp/test"]

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: ubuntu/xenial64
      box_url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box
      vm_hostname: ubuntu-xenial
      provision: true

provisioner:
  name: ansible_playbook
  playbook: ansible/site.yml
  roles_path: ansible/roles
  hosts: all
  ansible_verbose: true
  ansible_verbosity: 3
  require_chef_for_busser: false

verifier:
  name: serverspec

suites:
  - name: default
    verifier:
      patterns:
        - /tmp/test/integration/default/serverspec/default_spec.rb

