haproxy_public_ip: "0.0.0.0"

haproxy_stats_ip: "127.0.0.1"
haproxy_stats_port: "8888"

haproxy_appservers_ip: "127.0.0.1"
haproxy_appservers_port: "8080"
haproxy_appservers_backends:
   - name: app1
     address: "169.45.0.141"
     port: 443
   - name: app2
     address: "169.45.0.149"
     port: 443
   - name: app3
     address: "169.45.0.157"
     port: 443

haproxy_ssl_certfile: "cdn.pem"
haproxy_ssl_path: "/etc/haproxy/{{ haproxy_ssl_certfile }}"

haproxy_log_filename: "/var/log/haproxy.log"
haproxy_accesslog_filename: "/var/log/haproxy_access.log"
