- hosts: all
  roles:
    - haproxy
    - varnish
  gather_facts: false

  # Ansible requires python2, which is not installed by default on Ubuntu Xenial
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson

